### ISSUE TITLE
Crash when contacting trustix-daemon

### ISSUE THREAD

**Issue by davidak** [nix-community/trustix#83]
```
[root@gaming:~]# nix-build -E '(import <nixpkgs> {}).writeText "hello" "Hello World!"' --no-out-link --check
checking outputs of '/nix/store/fmvm1z6l9k78s6xcgbj8qkrhkbiz5ar4-hello.drv'...
running post-build-hook '/nix/store/7nzwfm3plmajjyvjvvry6vl2gyz3kvhd-trustix-hook'...
post-build-hook: time="2022-12-03T13:20:09+01:00" level=debug msg="Submitting mapping" storePath=/nix/store/cswi7m0frxljix1l6ixsjdryg5z75i3y-hello
post-build-hook: time="2022-12-03T13:20:09+01:00" level=debug msg="Creating client for remote" address="unix:///run/trustix-daemon.socket"
post-build-hook: panic: runtime error: invalid memory address or nil pointer dereference
post-build-hook: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7b55be]
post-build-hook: 
post-build-hook: goroutine 1 [running]:
post-build-hook: github.com/bufbuild/connect-go.newClientConfig({0xc0002b4200?, 0xc0002b4200?}, {0xc0001a9d68, 0x1, 0x90d240?})
post-build-hook:        github.com/bufbuild/connect-go/client.go:198 +0x1de
post-build-hook: github.com/bufbuild/connect-go.NewClient[...]({0xad43a0, 0xc00029aa20?}, {0xc0002b4200, 0x3f}, {0xc0001a9d68, 0x1, 0x1})
post-build-hook:        github.com/bufbuild/connect-go/client.go:41 +0xa9
post-build-hook: github.com/nix-community/trustix/packages/trustix-proto/api/apiconnect.NewLogAPIClient({0xad43a0, 0xc00029aa20}, {0x7ffd10f965b1?, 0x7?}, {0xc0001a9d68, 0x1, 0x1})
post-build-hook:        github.com/nix-community/trustix/packages/trustix-proto/api/apiconnect/api.connect.go:140 +0xcd
post-build-hook: github.com/nix-community/trustix/packages/trustix/client.newLogAPIConnectClient(...)
post-build-hook:        github.com/nix-community/trustix/packages/trustix/client/connect_logapi.go:23
post-build-hook: github.com/nix-community/trustix/packages/trustix/client.CreateClient({0x7ffd10f965b1, 0x21}, {0xc0001a9d68, 0x1, 0x1})
post-build-hook:        github.com/nix-community/trustix/packages/trustix/client/conn.go:35 +0x1d5
post-build-hook: github.com/nix-community/trustix/packages/trustix-nix/cmd.glob..func2(0xe4d820?, {0x9f4c1f?, 0x4?, 0x4?})
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/cmd/post-build-hook.go:87 +0x35d
post-build-hook: github.com/spf13/cobra.(*Command).execute(0xe4d820, {0xc0002c20c0, 0x4, 0x4})
post-build-hook:        github.com/spf13/cobra/command.go:872 +0x694
post-build-hook: github.com/spf13/cobra.(*Command).ExecuteC(0xe4daa0)
post-build-hook:        github.com/spf13/cobra/command.go:990 +0x3bd
post-build-hook: github.com/spf13/cobra.(*Command).Execute(...)
post-build-hook:        github.com/spf13/cobra/command.go:918
post-build-hook: github.com/nix-community/trustix/packages/trustix-nix/cmd.Execute()
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/cmd/root.go:57 +0x45
post-build-hook: main.main()
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/main.go:11 +0x17
error: program '/nix/store/7nzwfm3plmajjyvjvvry6vl2gyz3kvhd-trustix-hook' failed with exit code 2
```

This was also reported by @raboof in chat: https://matrix.to/#/!tCEqPTBHfrsSDeIuFP:trustix.dev/$3iWGOoZwyGMluozypjdK7jZMsCwkUvj9ud3alb-80bI?via=blad.is&via=matrix.org&via=nixos.dev

This issue is reproducible since e68812797d949a4b2b845318681f9455946a4a59, but might exist before and is hidden by other issues. Ref: https://github.com/nix-community/trustix/issues/81#issuecomment-1336453491

Tested on NixOS 22.05.4270.b68a6a27adb.

**Comment by davidak** [comment]
Here is a reproducible crash with the old version:

```
[davidak@gaming:~]$ nix-env -f channel:nixos-unstable -iA losslesscut-bin
installing 'losslesscut-3.48.2'
these 7 derivations will be built:
  /nix/store/5kf03qklngdx9smqnfh3k81r8yrlm62l-builder.pl.drv
  /nix/store/dyplay3433acsd7s6sxhapnfpx4nzsp5-losslesscut-3.48.2-usr-multi.drv
  /nix/store/7d6gx7vi8qzj16qbw52f5b68zf0pdmai-ldconfig.drv
  /nix/store/x4y3xr129dffhyyg9l521aaxz1ilhbms-losslesscut-3.48.2-usr-target.drv
  /nix/store/j13fmqk1sxzg8izm9g0phm0gw940nca4-losslesscut-3.48.2-fhs.drv
  /nix/store/55mz6hmhb67kbdw6a10vjpw4j8kx730g-losslesscut-3.48.2.drv
  /nix/store/41y4a9x9as56h657ws4hgd16mvbh1awg-losslesscut-3.48.2.drv
these 85 paths will be fetched (96.36 MiB download, 364.25 MiB unpacked):
  /nix/store/0a1fm55z6lylrg53nsw74k3xdsmicqn6-cups-2.4.2
  /nix/store/0h9w3gn2xp3v37r725v7djxlpz18d9f9-at-spi2-core-2.46.0
  /nix/store/0llvwv87d9gdg691dvpr8ascmcrcpblb-SDL_image-1.2.12
  /nix/store/1x10841jwbryi5sah3f6r0ksl88097y3-timidity-2.15.0
  /nix/store/25m9gvi0yp9bvqghx33jjzgpdfkpwb69-lttng-ust-2.13.1-dev
  /nix/store/28jwc5h31v9xjqxmnvgznbc2vfmzdp9g-SDL2_mixer-2.0.4
  /nix/store/3gx7a9gv4g4fsiapjr664yi6y2n3gn6d-mpg123-1.29.3
  /nix/store/44364skg2l1drldg4vdnzx5appxkh0c8-cryptsetup-2.5.0
  /nix/store/456ma5kr2xkayf9akwf6ka1yzdlq2f44-dbus-glib-0.112
  /nix/store/4i2q7ywiwjmn7q391r311q6vbfndg6rv-libusb-1.0.26
  /nix/store/4llb4ymwy2p7nwlq7imivwk7n2373zdq-SDL2-2.24.2
  /nix/store/5w51vszr5ahq3j908gr7axq3jz9v9rl2-at-spi2-core-2.46.0
  /nix/store/6av9nvm5bdvcw2hickxqljzlw14qph94-dbus-glib-0.112
  /nix/store/6p9vp3h30bl1zcdpayx93vfsg5cn2f7i-avahi-0.8
  /nix/store/6rxccvcxdm58bcpzzavh0bdc19fjba39-dbus-1.14.4
  /nix/store/75m6b701kl782pb8w2h121k71flzf5ki-pipewire-0.3.63-lib
  /nix/store/7hagh9syqv1djqad4ndfi7cz0a5h41gz-libmikmod-3.3.11.1
  /nix/store/7izw0ggi0ddcldlpx2hzljs5rncvryl5-SDL2_ttf-2.20.1
  /nix/store/7lcwbxizrk2hxyzhqvb142bvslj7vhrc-perl5.36.0-XML-Parser-2.46
  /nix/store/8mbmp69ad7zn0szx8rqrdc8vlcwdgnzf-bluez-5.66
  /nix/store/8xc9187i05z5vh3x6r8ggz1aldnwa8nn-avahi-0.8
  /nix/store/99npqps42lwz341gkl5j352grgmmkna3-SDL_mixer-1.2.12
  /nix/store/9rjdvhq7hnzwwhib8na2gmllsrh671xg-systemd-252.1
  /nix/store/az06bkcvnbw5788rk9x43qb2z7q7jkji-SDL2_image-2.0.5
  /nix/store/cd3mr3bihmg3g6v2yd18h4cg0s8i7ny8-libdbusmenu-gtk2-16.04.0
  /nix/store/chig00y5drdy3mz0aiq9a3phvc4g20xd-SDL-1.2.15
  /nix/store/cj9gjcsv9c7sb358251rcrj0ymglgxqy-roc-toolkit-0.1.5
  /nix/store/cp65c8nk29qq5cl1wyy5qyw103cwmax7-stdenv-linux
  /nix/store/cz32fr9sfcwchzy6nchp61ma7iasl98k-timidity-2.15.0
  /nix/store/dfxnn6adk78cq9fjzk1ipwyr86w1ba0f-lvm2-2.03.17-lib
  /nix/store/dghjjzldpiwj0f42jwplbwvgdfiyf1m3-libjack2-1.9.19
  /nix/store/f2ax95kbpk6f8k8ncmlmpi6pc4knq8kv-xdg-utils-unstable-2020-10-21
  /nix/store/f6n70r60p5lz402zpkjsx9jwa9chyp9v-libmikmod-3.3.11.1
  /nix/store/f9k3ifjhw0l01z0vk4ffjbvqpg6g3irb-fluidsynth-2.3.0
  /nix/store/fpbq4ph11yn2gk9xn605zxlvdbrgnspw-SDL-1.2.15
  /nix/store/gpwnc0615sgvl33rjwhk3j133dfvhxa6-SDL2_mixer-2.0.4
  /nix/store/gq75qjcx96mdfdbx4dmys2mqf3nh7nls-cups-2.4.2-lib
  /nix/store/h9y2c8wiiw8hnbpw44nixnk6qryd1y6j-lttng-ust-2.13.1-dev
  /nix/store/hc5hppwrh0zbqnr504nijldxpp75mg7h-libcanberra-0.30
  /nix/store/hmwkvvj8clxsvk0vacwvlpc4a4ax8s11-perl5.36.0-XML-Twig-3.52
  /nix/store/i8fxf1q385648kh5xv1kb9mhnpn4zzap-smpeg-0.4.5
  /nix/store/iagjpd42phw2pb7fbrnp0fpiq3jz4r2g-cups-2.4.2
  /nix/store/ibijgprlcfd9x3ka42x2b6j3cd6ygfym-libappindicator-gtk2-12.10.1+20.10.20200706.1
  /nix/store/jhrp91qhiyhhakcnns153iyvk6zh1cmi-systemd-252.1
  /nix/store/k7vq0q294i1kxzi19rgdqq9xyaxr2ng1-libudev0-shim-1
  /nix/store/kw9vlw7r0s0whjghih21dsn2731fxkhj-libudev0-shim-1
  /nix/store/ldlyfcm92wz0pmc4jcrq3mppk0907x5y-libjack2-1.9.19
  /nix/store/lyvgw6wxb61l2c1krpr2hzprd34cms4v-dbus-1.14.4-lib
  /nix/store/m8q73428vam476mjzrn8fzgyynnnngnl-SDL_ttf-2.0.11
  /nix/store/mhfz7w4iv0kapdzhwzagxd9cxhpk8bi0-roc-toolkit-0.1.5
  /nix/store/n0wl9krwfwdgdwx8xhiay9mlgllczy2b-perl5.36.0-Net-DBus-1.2.0
  /nix/store/ng0c8jyqpw4sxdsjni5701i5gnsp3p5z-libtool-2.4.7
  /nix/store/nhffrd7f15dhfbkwzgayq7hhzmdvdy19-pipewire-0.3.63-lib
  /nix/store/nzgagfn23rajmkbwpd0mal82a5vp4hf6-libpulseaudio-16.1
  /nix/store/pd0yilrfsyg33dzj8ha3nf2qsklvb90q-gtk+-2.24.33
  /nix/store/qq5gxg29p3fs3vifsl19fy6nd4z1ni75-libcanberra-0.30
  /nix/store/qwhfr3pprbwzkcdji0amkwxkla1r4xxf-libappindicator-gtk2-12.10.1+20.10.20200706.1
  /nix/store/rc7mizqyddax1whb3qnpqw9b7cqabj6p-SDL2_ttf-2.20.1
  /nix/store/ri5nzca147wk53xqg75c3f4n6529rn4g-mpg123-1.29.3
  /nix/store/rv6nydaizz3n8s3l3jv6pss0pzxn3yzm-gtk+3-3.24.35
  /nix/store/rwh0b2ipyp6fs3a22vjzw4p1zab1kx8l-cryptsetup-2.5.0
  /nix/store/rybnwbk326kircfrjlldx1y7y9ydk1gi-libfido2-1.12.0
  /nix/store/sjs7szvhvyjzlmgzqn7g1la2bkl5kqjz-libtool-2.4.7
  /nix/store/vha7kz0yif4aihk0143nq8ysl6v2m1hz-libdbusmenu-gtk2-16.04.0
  /nix/store/vhfi88ilb8gb4357cj392k78l5nq2na1-lvm2-2.03.17-lib
  /nix/store/vmwpa824n16v7gf350xprad5bzy2ckp7-SDL_image-1.2.12
  /nix/store/vpxmjp3s1w8zry7xlydq5rkvzimnma2z-SDL_mixer-1.2.12
  /nix/store/vqg16chb5dgg3ihxgpwvnickws8q3wd0-libusb-1.0.26
  /nix/store/w6hkmy99jw3fgddqzc7cnhar4x7k64sw-libdecor-0.1.0
  /nix/store/w7pyqbv1klndmbm2qwdilfirhv08y0p1-SDL2-2.24.2
  /nix/store/wn3jnv9351r59rplrvkvlx559bj697n6-libcamera-0.0.1
  /nix/store/wrb22wvw060j82ald8pafl2iakpxyph6-libdecor-0.1.0
  /nix/store/ww063smpzmc6jmhflflqs35g7gp1j9fx-libpulseaudio-16.1
  /nix/store/wyryhglai0m0mf5ajmdkk2pa9kwwr3xj-libfido2-1.12.0
  /nix/store/wz14i9kz0ick2an8v2391x67d6iw65kn-gtk+-2.24.33
  /nix/store/wz2l9xabd1rz2kdqqg2vn451x166d88c-libcamera-0.0.1
  /nix/store/x74c855nqp1h2vc0zsbhz1i2lcaik8l6-fluidsynth-2.3.0
  /nix/store/xbzkffl6akgbc1cmjxy708rj4wbs5f2l-dbus-1.14.4
  /nix/store/xl77crlw2jnm6831gwr706civll59i1a-dbus-1.14.4-lib
  /nix/store/xy5z1jzmvr5sgbrb9dknw11c3k8nh9gq-bluez-5.66
  /nix/store/y10l6lvpp6vs8frqsz35rjyz9jbjy1ji-smpeg-0.4.5
  /nix/store/ywszsbpp7d36wpgmnksr3xzl640xz4n1-cups-2.4.2-lib
  /nix/store/z4354ac2m7fm69bmfk6zsz5dsx1j1w4m-SDL2_image-2.0.5
  /nix/store/z7sw1r36cpgsva1cbw5c1pasn0qabzpq-zenity-3.43.0
  /nix/store/zx8zv7faqq9fpz8qcw7k2khigrip3z9l-SDL_ttf-2.0.11
copying path '/nix/store/cp65c8nk29qq5cl1wyy5qyw103cwmax7-stdenv-linux' from 'https://cache.nixos.org'...
copying path '/nix/store/lyvgw6wxb61l2c1krpr2hzprd34cms4v-dbus-1.14.4-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/xl77crlw2jnm6831gwr706civll59i1a-dbus-1.14.4-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/sjs7szvhvyjzlmgzqn7g1la2bkl5kqjz-libtool-2.4.7' from 'https://cache.nixos.org'...
copying path '/nix/store/ng0c8jyqpw4sxdsjni5701i5gnsp3p5z-libtool-2.4.7' from 'https://cache.nixos.org'...
copying path '/nix/store/4i2q7ywiwjmn7q391r311q6vbfndg6rv-libusb-1.0.26' from 'https://cache.nixos.org'...
copying path '/nix/store/vqg16chb5dgg3ihxgpwvnickws8q3wd0-libusb-1.0.26' from 'https://cache.nixos.org'...
building '/nix/store/5kf03qklngdx9smqnfh3k81r8yrlm62l-builder.pl.drv'...
building '/nix/store/7d6gx7vi8qzj16qbw52f5b68zf0pdmai-ldconfig.drv'...
copying path '/nix/store/rybnwbk326kircfrjlldx1y7y9ydk1gi-libfido2-1.12.0' from 'https://cache.nixos.org'...
copying path '/nix/store/wyryhglai0m0mf5ajmdkk2pa9kwwr3xj-libfido2-1.12.0' from 'https://cache.nixos.org'...
copying path '/nix/store/7lcwbxizrk2hxyzhqvb142bvslj7vhrc-perl5.36.0-XML-Parser-2.46' from 'https://cache.nixos.org'...
copying path '/nix/store/dfxnn6adk78cq9fjzk1ipwyr86w1ba0f-lvm2-2.03.17-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/vhfi88ilb8gb4357cj392k78l5nq2na1-lvm2-2.03.17-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/h9y2c8wiiw8hnbpw44nixnk6qryd1y6j-lttng-ust-2.13.1-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/25m9gvi0yp9bvqghx33jjzgpdfkpwb69-lttng-ust-2.13.1-dev' from 'https://cache.nixos.org'...
running post-build-hook '/nix/store/7nzwfm3plmajjyvjvvry6vl2gyz3kvhd-trustix-hook'...
post-build-hook: time="2022-12-18T20:30:26+01:00" level=debug msg="Submitting mapping" storePath=/nix/store/xrnhz02n20rb06h4rda9d4fc3h1y9cl3-builder.pl
post-build-hook: time="2022-12-18T20:30:26+01:00" level=debug msg="Creating client for remote" address="unix:///run/trustix-daemon.socket"
post-build-hook: panic: runtime error: invalid memory address or nil pointer dereference
post-build-hook: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7b55be]
post-build-hook: 
post-build-hook: goroutine 1 [running]:
post-build-hook: github.com/bufbuild/connect-go.newClientConfig({0xc0001402c0?, 0xc0001402c0?}, {0xc000197d68, 0x1, 0x90d240?})
post-build-hook:        github.com/bufbuild/connect-go/client.go:198 +0x1de
post-build-hook: github.com/bufbuild/connect-go.NewClient[...]({0xad43a0, 0xc000124900?}, {0xc0001402c0, 0x3f}, {0xc000197d68, 0x1, 0x1})
post-build-hook:        github.com/bufbuild/connect-go/client.go:41 +0xa9
post-build-hook: github.com/nix-community/trustix/packages/trustix-proto/api/apiconnect.NewLogAPIClient({0xad43a0, 0xc000124900}, {0x7ffedc267d4f?, 0x7?}, {0xc000197d68, 0x1, 0x1})
post-build-hook:        github.com/nix-community/trustix/packages/trustix-proto/api/apiconnect/api.connect.go:140 +0xcd
post-build-hook: github.com/nix-community/trustix/packages/trustix/client.newLogAPIConnectClient(...)
post-build-hook:        github.com/nix-community/trustix/packages/trustix/client/connect_logapi.go:23
post-build-hook: github.com/nix-community/trustix/packages/trustix/client.CreateClient({0x7ffedc267d4f, 0x21}, {0xc000197d68, 0x1, 0x1})
post-build-hook:        github.com/nix-community/trustix/packages/trustix/client/conn.go:35 +0x1d5
post-build-hook: github.com/nix-community/trustix/packages/trustix-nix/cmd.glob..func2(0xe4d820?, {0x9f4c1f?, 0x4?, 0x4?})
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/cmd/post-build-hook.go:87 +0x35d
post-build-hook: github.com/spf13/cobra.(*Command).execute(0xe4d820, {0xc00014e0c0, 0x4, 0x4})
post-build-hook:        github.com/spf13/cobra/command.go:872 +0x694
post-build-hook: github.com/spf13/cobra.(*Command).ExecuteC(0xe4daa0)
post-build-hook:        github.com/spf13/cobra/command.go:990 +0x3bd
post-build-hook: github.com/spf13/cobra.(*Command).Execute(...)
post-build-hook:        github.com/spf13/cobra/command.go:918
post-build-hook: github.com/nix-community/trustix/packages/trustix-nix/cmd.Execute()
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/cmd/root.go:57 +0x45
post-build-hook: main.main()
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/main.go:11 +0x17
error: program '/nix/store/7nzwfm3plmajjyvjvvry6vl2gyz3kvhd-trustix-hook' failed with exit code 2
```

I run it multiple times and Nix builds more and more...

```
[davidak@gaming:~]$ nix-env -f channel:nixos-unstable -iA losslesscut-bin
installing 'losslesscut-3.48.2'
this derivation will be built:
  /nix/store/41y4a9x9as56h657ws4hgd16mvbh1awg-losslesscut-3.48.2.drv
building '/nix/store/41y4a9x9as56h657ws4hgd16mvbh1awg-losslesscut-3.48.2.drv'...
running post-build-hook '/nix/store/7nzwfm3plmajjyvjvvry6vl2gyz3kvhd-trustix-hook'...
post-build-hook: time="2022-12-18T20:34:16+01:00" level=debug msg="Submitting mapping" storePath=/nix/store/r5h7mang5dnr7yfkgck6w4v2335y973f-losslesscut-3.48.2
post-build-hook: time="2022-12-18T20:34:16+01:00" level=debug msg="Creating client for remote" address="unix:///run/trustix-daemon.socket"
post-build-hook: panic: runtime error: invalid memory address or nil pointer dereference
post-build-hook: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7b55be]
post-build-hook: 
post-build-hook: goroutine 1 [running]:
post-build-hook: github.com/bufbuild/connect-go.newClientConfig({0xc00015c7c0?, 0xc00015c7c0?}, {0xc0001a3d68, 0x1, 0x90d240?})
post-build-hook:        github.com/bufbuild/connect-go/client.go:198 +0x1de
post-build-hook: github.com/bufbuild/connect-go.NewClient[...]({0xad43a0, 0xc00023cc30?}, {0xc00015c7c0, 0x3f}, {0xc0001a3d68, 0x1, 0x1})
post-build-hook:        github.com/bufbuild/connect-go/client.go:41 +0xa9
post-build-hook: github.com/nix-community/trustix/packages/trustix-proto/api/apiconnect.NewLogAPIClient({0xad43a0, 0xc00023cc30}, {0x7fffac31ed3f?, 0x7?}, {0xc0001a3d68, 0x1, 0x1})
post-build-hook:        github.com/nix-community/trustix/packages/trustix-proto/api/apiconnect/api.connect.go:140 +0xcd
post-build-hook: github.com/nix-community/trustix/packages/trustix/client.newLogAPIConnectClient(...)
post-build-hook:        github.com/nix-community/trustix/packages/trustix/client/connect_logapi.go:23
post-build-hook: github.com/nix-community/trustix/packages/trustix/client.CreateClient({0x7fffac31ed3f, 0x21}, {0xc0001a3d68, 0x1, 0x1})
post-build-hook:        github.com/nix-community/trustix/packages/trustix/client/conn.go:35 +0x1d5
post-build-hook: github.com/nix-community/trustix/packages/trustix-nix/cmd.glob..func2(0xe4d820?, {0x9f4c1f?, 0x4?, 0x4?})
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/cmd/post-build-hook.go:87 +0x35d
post-build-hook: github.com/spf13/cobra.(*Command).execute(0xe4d820, {0xc000163040, 0x4, 0x4})
post-build-hook:        github.com/spf13/cobra/command.go:872 +0x694
post-build-hook: github.com/spf13/cobra.(*Command).ExecuteC(0xe4daa0)
post-build-hook:        github.com/spf13/cobra/command.go:990 +0x3bd
post-build-hook: github.com/spf13/cobra.(*Command).Execute(...)
post-build-hook:        github.com/spf13/cobra/command.go:918
post-build-hook: github.com/nix-community/trustix/packages/trustix-nix/cmd.Execute()
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/cmd/root.go:57 +0x45
post-build-hook: main.main()
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/main.go:11 +0x17
error: program '/nix/store/7nzwfm3plmajjyvjvvry6vl2gyz3kvhd-trustix-hook' failed with exit code 2
```

```
[davidak@gaming:~]$ nix-env -f channel:nixos-unstable -iA losslesscut-bin
installing 'losslesscut-3.48.2'
building '/nix/store/wj2qwk57nvjwm89adj9wmv4kfp89mmdq-user-environment.drv'...
running post-build-hook '/nix/store/7nzwfm3plmajjyvjvvry6vl2gyz3kvhd-trustix-hook'...
post-build-hook: time="2022-12-18T20:35:31+01:00" level=debug msg="Submitting mapping" storePath=/nix/store/jjgi2fdwag7v1mxnrad8792csypcjnw0-user-environment
post-build-hook: time="2022-12-18T20:35:31+01:00" level=debug msg="Creating client for remote" address="unix:///run/trustix-daemon.socket"
post-build-hook: panic: runtime error: invalid memory address or nil pointer dereference
post-build-hook: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7b55be]
post-build-hook: 
post-build-hook: goroutine 1 [running]:
post-build-hook: github.com/bufbuild/connect-go.newClientConfig({0xc00002e380?, 0xc00002e380?}, {0xc0001a3d68, 0x1, 0x90d240?})
post-build-hook:        github.com/bufbuild/connect-go/client.go:198 +0x1de
post-build-hook: github.com/bufbuild/connect-go.NewClient[...]({0xad43a0, 0xc0000a6960?}, {0xc00002e380, 0x3f}, {0xc0001a3d68, 0x1, 0x1})
post-build-hook:        github.com/bufbuild/connect-go/client.go:41 +0xa9
post-build-hook: github.com/nix-community/trustix/packages/trustix-proto/api/apiconnect.NewLogAPIClient({0xad43a0, 0xc0000a6960}, {0x7ffd879c4d43?, 0x7?}, {0xc0001a3d68, 0x1, 0x1})
post-build-hook:        github.com/nix-community/trustix/packages/trustix-proto/api/apiconnect/api.connect.go:140 +0xcd
post-build-hook: github.com/nix-community/trustix/packages/trustix/client.newLogAPIConnectClient(...)
post-build-hook:        github.com/nix-community/trustix/packages/trustix/client/connect_logapi.go:23
post-build-hook: github.com/nix-community/trustix/packages/trustix/client.CreateClient({0x7ffd879c4d43, 0x21}, {0xc0001a3d68, 0x1, 0x1})
post-build-hook:        github.com/nix-community/trustix/packages/trustix/client/conn.go:35 +0x1d5
post-build-hook: github.com/nix-community/trustix/packages/trustix-nix/cmd.glob..func2(0xe4d820?, {0x9f4c1f?, 0x4?, 0x4?})
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/cmd/post-build-hook.go:87 +0x35d
post-build-hook: github.com/spf13/cobra.(*Command).execute(0xe4d820, {0xc000098100, 0x4, 0x4})
post-build-hook:        github.com/spf13/cobra/command.go:872 +0x694
post-build-hook: github.com/spf13/cobra.(*Command).ExecuteC(0xe4daa0)
post-build-hook:        github.com/spf13/cobra/command.go:990 +0x3bd
post-build-hook: github.com/spf13/cobra.(*Command).Execute(...)
post-build-hook:        github.com/spf13/cobra/command.go:918
post-build-hook: github.com/nix-community/trustix/packages/trustix-nix/cmd.Execute()
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/cmd/root.go:57 +0x45
post-build-hook: main.main()
post-build-hook:        github.com/nix-community/trustix/packages/trustix-nix/main.go:11 +0x17
error: program '/nix/store/7nzwfm3plmajjyvjvvry6vl2gyz3kvhd-trustix-hook' failed with exit code 2
```

```
[davidak@gaming:~]$ nix-env -f channel:nixos-unstable -iA losslesscut-bin
installing 'losslesscut-3.48.2'
```
